## MODULE
module:
    hugoVersion:
        min: "0.93.0"
        max: "0.93.0"

## PARAMS
params:
  keycdn: https://osuny-1b4da.kxcdn.com
  cookie_banner:
    enable: true
    blank: true
    page: https://gdpr.eu/cookies/
