name = "Osuny School"
license = "MIT"
licenselink = "https://github.com/noesya/hugo-osuny/blob/master/LICENSE"
description = "Hugo theme for Osuny websites"
homepage = "https://www.osuny.org"
tags = []
features = []
min_version = "0.91.0"

[author]
  name = "noesya"
  homepage = "https://www.noesya.coop"
